# Site settings
title: Refac Tools - Command-Line Tool Suite
description: >-
  A comprehensive suite of command-line tools for file management, string replacement, 
  temporary storage, and version control. Includes refac (string replacement), 
  scrap (smart file management), unscrap (file restoration), and verbump (automatic versioning).
author: Bahram Shamshiri
email: jowharshamshiri@gmail.com
baseurl: "/refac"
url: "https://jowharshamshiri.github.io"

# Build settings
theme: jekyll-theme-minimal
markdown: kramdown
highlighter: rouge

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-relative-links
  - jekyll-toc
  - jekyll-github-metadata

# Permalink structure
permalink: /:title/

# Navigation
navigation:
  - title: Home
    url: /
  - title: Getting Started
    url: /getting-started/
  - title: Installation
    url: /installation/
  - title: Tool Guides
    subnav:
      - title: Scrap Guide
        url: /scrap-guide/
      - title: Unscrap Guide
        url: /unscrap-guide/
      - title: Verbump Guide
        url: /verbump-guide/
  - title: Usage Guide
    url: /usage/
  - title: API Reference
    url: /api-reference/
  - title: Examples
    url: /examples/
  - title: Contributing
    url: /contributing/

# GitHub repository information
repository: jowharshamshiri/refac
github:
  repository_name: refac
  repository_nwo: jowharshamshiri/refac

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .sass-cache/
  - .jekyll-cache/
  - .jekyll-metadata

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      toc: true