# Site settings
title: Nomion - Command-Line Tool Suite
description: >-
  Nomion is a tool suite for file operations, version management, 
  and development workflow automation. Includes refac (string replacement), scrap (local trash folder), 
  unscrap (file restoration), and st8 (automatic versioning).
author: Bahram Shamshiri
email: jowharshamshiri@gmail.com
baseurl: "/nomion"
url: "https://jowharshamshiri.github.io"

# Build settings
theme: jekyll-theme-minimal
markdown: kramdown
highlighter: rouge

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-relative-links
  - jekyll-toc
  - jekyll-github-metadata

# Permalink structure
permalink: /:title/

# Navigation
navigation:
  - title: Home
    url: /
  - title: Getting Started
    url: /getting-started/
  - title: Installation
    url: /installation/
  - title: Tool Guides
    subnav:
      - title: Scrap Guide
        url: /scrap-guide/
      - title: Unscrap Guide
        url: /unscrap-guide/
      - title: St8 Guide
        url: /st8-guide/
  - title: Usage Guide
    url: /usage/
  - title: API Reference
    url: /api-reference/
  - title: Examples
    url: /examples/
  - title: Contributing
    url: /contributing/

# GitHub repository information
repository: jowharshamshiri/nomion
github:
  repository_name: nomion
  repository_nwo: jowharshamshiri/nomion

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .sass-cache/
  - .jekyll-cache/
  - .jekyll-metadata

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      toc: true