title: Refac Tool
description: Robust cross-platform tool for recursive string replacement
theme: jekyll-theme-cayman
plugins:
  - jekyll-relative-links
  - jekyll-seo-tag

collections:
  examples:
    output: true
    permalink: /examples/:path/

defaults:
  - scope:
      path: ""
    values:
      layout: default
      toc: true