source "https://rubygems.org"

gem "jekyll", "~> 4.3.2"
gem "jekyll-theme-minimal", "~> 0.2.0"
gem "jekyll-seo-tag", "~> 2.8"
gem "jekyll-sitemap", "~> 1.4"
gem "jekyll-feed", "~> 0.17"
gem "jekyll-relative-links", "~> 0.7"
gem "jekyll-toc", "~> 0.18"
gem "jekyll-github-metadata", "~> 2.16"

# Windows and JRuby compatibility
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1", :install_if => Gem.win_platform?