name: Deploy GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Build Jekyll site
      uses: actions/jekyll-build-pages@v1
      with:
        source: ./docs
        destination: ./_site

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2

    - name: Deploy
      uses: actions/deploy-pages@v3